package zzz.bing.himalaya.utils

const val RECOMMEND_COUNT = 30

const val MEDIUM_EXPAND_DURATION = 250L
const val MEDIUM_COLLAPSE_DURATION = 200L

const val LARGE_EXPAND_DURATION = 300L
const val LARGE_COLLAPSE_DURATION = 250L